#!/usr/bin/python -O
from pyglet.gl import GLfloat,glColor3fv,glClear,GL_COLOR_BUFFER_BIT,glRecti
from pyglet.graphics import draw
from pyglet.clock import set_fps_limit as a,tick
a(30)
from pyglet.window import Window as W
from os import listdir as LvL
LvL=iter(sorted(LvL for LvL in LvL(".") if LvL.endswith(".txt"))).next                                                 
from random import random,choice
from math import pi,cos,sin
W=W(fullscreen=True)
W.maximize()
Hei=W.height
Wid=W.width
GLfloat*=3
Col=GLfloat(0.,0.,0.),GLfloat(0.,0.,1.),GLfloat(0.,1.,0.),GLfloat(0.,1.,1.),GLfloat(1.,0.,0.),GLfloat(1.,0.,1.),GLfloat(1.,1.,0.),GLfloat(1.,1.,1.)
GLfloat.H=True
GLfloat.C=property(lambda s:s)
class Nil:H=False
class Ply:
	def __init__(s,*x):
		s.x,s.y,s.d=x or (P.x,P.y,P.d)
		if x:
			globals()["P"]=s
			@W.event
			def on_mouse_press(x,y,X,Y,D={(-1,-1):s.lwd,(-1,0):s.lwd,(-1,1):s.ltr,(0,-1):s.bwd,(0,0):s.fwd,(0,1):s.fwd,(1,-1):s.rwd,(1,0):s.rwd,(1,1):s.rtr}):
				if X==4:return kenter()
				X=s.x,s.y
				D[-(x<Wid//3) or x>(Wid<<1)//3,-(y<Hei//3) or y>(Hei<<1)//3]()
				if not(0<=s.y<len(L) and 0<=s.x<len(L[0])) or L[s.y][s.x].H:s.x,s.y=X
	def ltr(s):s.d=s.d+1&3
	def rtr(s):s.d=s.d-1&3
	def fwd(s):
		s.x+=(1,0,-1,0)[s.d]
		s.y+=(0,-1,0,1)[s.d]
	def bwd(s):
		s.x+=(-1,0,1,0)[s.d]
		s.y+=(0,1,0,-1)[s.d]
	def lwd(s,x=1):
		s.x+=(0,x,0,-x)[s.d]
		s.y+=(x,0,-x,0)[s.d]
		return s
	def rwd(s,x=1):
		s.x+=(0,-x,0,x)[s.d]
		s.y+=(-x,0,x,0)[s.d]
		return s
Win=type("",(),{"C":property(lambda s:choice(Col)),"H":property(lambda s:not mkL())})()
def mkL(Lv=None):
	if Lv is None:Lv=LvL()
	globals()["kenter"]=lambda:mkL(Lv)
	L=open(Lv).read().split("\n")
	mL=max(map(len,L))
	globals()["L"]=[[Nil if L in " 0" else Win if L=="!" else Ply(x,y,">^<v".index(L)) and Nil if L in ">^<v" else Col[int(L)] if L in "1234567" else GLfloat(random(),random(),random()) for x,L in enumerate(L)]+[Nil]*(mL-len(L)) for y,L in enumerate(L)]
	for mL in reversed(Col):
		glColor3fv(mL)
		glRecti(0,0,Wid,Hei)
		W.flip()
		tick()
W.dispatch_events()
mkL()
while not W.has_exit:
	tick()
	W.dispatch_events()
	glClear(GL_COLOR_BUFFER_BIT)
	for b,a in enumerate((Ply().lwd().lwd(),Ply().lwd(),Ply(),Ply().rwd(),Ply().rwd().rwd())):
		while 0<=a.y<len(L) and 0<=a.x<len(L[0]) and L[a.y][a.x] is Nil:a.fwd()
		glColor3fv(L[a.y][a.x].C if 0<=a.y<len(L) and 0<=a.x<len(L[0]) else Col[0])
		glRecti(Wid*b//5,Hei//3,Wid*(b+1)//5,(Hei<<1)//3)
	glColor3fv(choice(Col))
	draw(10,1,("v2f",(Wid//3,0,Wid//3,Hei,(Wid<<1)//3,0,(Wid<<1)//3,Hei,Wid//3,Hei//3,(Wid<<1)//3,Hei//3,0,(Hei<<1)//3,Wid//3,(Hei<<1)//3,(Wid<<1)//3,(Hei<<1)//3,Wid,(Hei<<1)//3)))
	W.flip()
